services:
  jupyter:
    build: 
      context: .
      args:
        ENV_YML: "environment.yaml"
        VENV: "bioinfo"
        DIR_CONDA: "/opt/conda"
        REQ_TXT: "requirements.txt"
    image: kojamad28/jupyter-bioinformatics
    container_name: jupyterlab
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - .:/usr/src/app
    tty: true
    stdin_open: true
